apiVersion: v1
kind: Service
metadata:
  name: {{ include "jobrm.fullname" . }}
  labels:
    app: {{ include "jobrm.name" . }}
    chart: {{ include "jobrm.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      nodePort: {{.Values.service.nodePort}}
  selector:
    app: {{ include "jobrm.name" . }}
    release: {{ .Release.Name }}
