# Default values for jobrm2.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: jobrm
  tag: latest

nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 80
  nodePort: 31001

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
